### ISSUE TITLE
[Feature Request] Lista sekcji / klikalność elementów

### ISSUE THREAD

**Issue by kamirr** [nastoletni/faq#5]
Teraz sprawa wygląda bardzo dziwnie, bo niby są przyciski, ale jako odnośniki działają tylko napisy na nich, gdzieś indziej dzieją się dziwne rzeczy i dodanie do znaczników `a` stylu `display:block;` nie wystarczy żeby wypełniły całą przestrzeń elementu listy.

Ktoś bardziej rozgarnięty we front–endzie się tym zajmie, całość zostaje tak jak jest czy dorzucić do .css jakąś prostą klasę i poprawić HTML tym moim prawie–dobrym rozwiązaniem?

**Comment by Albert221** [comment]
Wystarczy, że dodasz dla `a` `display: block` i przeniesiesz `padding` z `.table-of-contents > ol > li` do potomka `a`. Jednak to musisz zrobić w https://github.com/nastoletni/sass

**Comment by Albert221** [comment]
Zrobione https://github.com/nastoletni/sass/commit/5690de23c14c8dfeae9196c041d45487bcfce292
